#!/bin/python
import csv
import sys

def main():
    if len(sys.argv) == 2:
        arg()
    ask = str(input("Search or add   ?: "))
    if ask.lower() in "add":
        add()
    elif ask.lower() in "search":
        search()
    else:
        print("  Usage: type either search or add !")
        sys.exit(1)
def add():
    with open("contacts.csv","a") as file:
        name = str(input("Name  : "))
        number = int(input("Number  : "))
        writer = csv.writer(file)
        writer.writerow([name, number])

def search():
    with open("contacts.csv","r") as file:
        query = str(input('Name to search for  : '))
        for line in file.readlines():
            if query in line.lower():
                print(line.rstrip())
def arg():
        if sys.argv[1] in "search":
            search()
        else:
            add()

if __name__ == "__main__":
    main()
